### PR TITLE
Created a navigation bar

### PR DESCRIPTION
**Pull request by godwin-morwin**
created a responsive navbar

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Comment by vinzvinci** [comment]
oh wait, I didn't notice that you break important features. You just broke the site, we can't merge this. I will revert this!

**Comment by godwin-morwin** [comment]
> oh wait, I didn't notice that you break important features. You just broke the site, we can't merge this. I will revert this!

i am so so very sorry i did

**Comment by vinzvinci** [comment]
No worries, I will take the issue so everything will be solved. This event is already launched.

**Comment by godwin-morwin** [comment]
thanks @vinzvinci

**Pull request merged**
